eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8899/eureka/
server:
  port: 8900
spring:
  application:
    name: service-core
  data:
    mongodb:
      host: localhost
      port: 27017
      database: mongo

